# Generated by Django 4.2.23 on 2025-06-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothe',
            name='base_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base price in CLP', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='clothe',
            name='gid',
            field=models.CharField(blank=True, help_text='Shopify Global ID', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clothe',
            name='shopify_id',
            field=models.BigIntegerField(blank=True, help_text='Shopify product ID', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clothe',
            name='variants',
            field=models.JSONField(blank=True, default=list, help_text='Product variants with size, price, SKU info'),
        ),
        migrations.AddField(
            model_name='clothe',
            name='vendor',
            field=models.CharField(blank=True, help_text='Product vendor/brand', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clothe',
            name='type',
            field=models.CharField(choices=[('SHIRT', 'Shirt'), ('PANTS', 'Pants'), ('DRESS', 'Dress'), ('SHOES', 'Shoes'), ('JACKET', 'Jacket'), ('SWEATER', 'Sweater'), ('SHORTS', 'Shorts'), ('SKIRT', 'Skirt'), ('BLOUSE', 'Blouse'), ('HOODIE', 'Hoodie'), ('COAT', 'Coat'), ('JEANS', 'Jeans'), ('ACCESSORIES', 'Accessories'), ('POLERA', 'Polera'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
        migrations.AddIndex(
            model_name='clothe',
            index=models.Index(fields=['shopify_id'], name='api_clothe_shopify_940257_idx'),
        ),
        migrations.AddIndex(
            model_name='clothe',
            index=models.Index(fields=['vendor'], name='api_clothe_vendor_1838ba_idx'),
        ),
        migrations.AddIndex(
            model_name='clothe',
            index=models.Index(fields=['type'], name='api_clothe_type_4e5c97_idx'),
        ),
    ]
